name: Run Tests
on:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest==6.2.4 pytest-cov==2.12.1 pytest-mock==3.6.1

      - name: Run pytest
        run: |
          PYTHONPATH=. pytest tests

      - name: Run pytest (with coverage)
        run: |
          PYTHONPATH=. pytest --cov=lib tests/ | tee pytest-coverage.txt

      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
